### ISSUE TITLE
exact makeup of the overview.html files remains unclear

### ISSUE THREAD

**Issue by TheGhost2804** [msorens/DocTreeGenerator#3]
Basic HTML returns unclear errors:
*\* Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "'"' is an unexpected token. Expecting white space. Line 1, position 63."

This goes for all overview files.

**Comment by msorens** [comment]
Please zip up your relevant file tree and attach to your issue report so I can try to reproduce your problem. Also, please provide the exact command-line you typed. If you have proprietary information that you cannot send, at a minimum I would need to have a copy of your overview files and I will be happy to look into the problem you are having.

**Comment by TheGhost2804** [comment]
well, I fixed this specific error (it was missing a space in the doctype definition) but now it keeps saying:
*\* The property 'body' cannot be found on this object. Verify that the property exists.
*\* Missing summary (from namespace_overview.html)

[namespace_overview.zip](https://github.com/msorens/DocTreeGenerator/files/206890/namespace_overview.zip)

**Comment by msorens** [comment]
Thanks for the file; that helped me isolate the issue. It turns out that just the presence of the doctype definition (DTD) altered the internal XML representation of the HTML. So when trying to retrieve `$data.html.body` it was not there. (Turns out it moved to `$data.html[1].body`.) So the workaround with the current version is to simply remove your DTD. 

I am going to leave this issue active and will address it in the next release. Thanks for finding this!

**Comment by msorens** [comment]
Added support for DTDs in the overview HTML files in Release 2.0.05.
