### ISSUE TITLE
Publish DTG on PowerShell Gallery

### ISSUE THREAD

**Issue by ebekker** [msorens/DocTreeGenerator#6]
Would it be possible to publish DocTreeGenerator to the PS Gallery?  That would make the tool much more accessible in *the PowerShell way*.

**Comment by msorens** [comment]
Excellent suggestion, Eugene, and that has been on my "to-do" list for sometime. Since you raised the issue, though, I will bump it up in priority. :-) I've not published to the PS Gallery before, but it looks like it is just a matter of using Publish-Module, is that correct? If you have any tips or links on doing so, please pass them along.

**Comment by ebekker** [comment]
It's very straightforward:
* You just need to [sign in](https://www.powershellgallery.com/users/account/LogOn) to the gallery using any valid MS account (Azure, Outlook.com, Office 365, etc.).  (The first time you use a new account, there might be some basic registration to complete.)
* Once you sign in, go to your [account profile](https://www.powershellgallery.com/account) and copy the **API Key**.
* On the PS command line, then you issue the `Publish-Module` as you said:
```powershell
$PSGalleryApiKey = '(Your API Key)'
Publish-Module -Path path/to/your/module/folder -NuGetApiKey $PSGalleryApiKey
```

That should be it.  To republish your module, you just need to make sure that you bump up your version number.

**Comment by msorens** [comment]
Done with release 2.0.08. (Not quite so straightforward :-)as I needed to update and fill-in requisite fields in the manifest, but well worth doing!)
